from yacs.config import CfgNode as CN

_C = CN()

_C.DRUG = CN()
_C.DRUG.NODE_IN_FEATS = 75
_C.DRUG.PADDING = True
_C.DRUG.HIDDEN_LAYERS = [128, 128, 128]
_C.DRUG.NODE_IN_EMBEDDING = 128
_C.DRUG.MAX_NODES = 290

_C.PROTEIN = CN()
_C.PROTEIN.NUM_FILTERS = [128, 128, 128]
_C.PROTEIN.EMBEDDING_DIM = 128
_C.PROTEIN.NUM_HEAD = 8
_C.PROTEIN.PADDING = True
_C.PROTEIN.USE_ESM2 = False
_C.PROTEIN.USE_PROTT5 = False

# Protein Language Model — uncomment one block to switch models
# ESM-2 35M
# _C.PROTEIN.MODEL_PATH = "../../../esm2_t12_35M_UR50D"
# _C.PROTEIN.MODEL_TYPE = "esm2"
# _C.PROTEIN.HIDDEN_DIM = 480

# ESM-2 650M
# _C.PROTEIN.MODEL_PATH = "../../../esm2_t33_650M_UR50D"
# _C.PROTEIN.MODEL_TYPE = "esm2"
# _C.PROTEIN.HIDDEN_DIM = 1280

# ProtT5-XL (default) — download from Zenodo and place at ../../../prot_t5_xl_uniref50
_C.PROTEIN.MODEL_PATH = "../../../prot_t5_xl_uniref50"
_C.PROTEIN.MODEL_TYPE = "prott5"
_C.PROTEIN.HIDDEN_DIM = 1024

_C.PROTEIN.ESM_MODEL_PATH = _C.PROTEIN.MODEL_PATH
_C.PROTEIN.ESM_HIDDEN_DIM = _C.PROTEIN.HIDDEN_DIM

_C.PROTEIN.MAX_LENGTH = 1200
_C.PROTEIN.ADAPTER_LAYERS = 3
_C.PROTEIN.USE_TRANSFORMER = False
_C.PROTEIN.TRANSFORMER_LAYERS = 2
_C.PROTEIN.TRANSFORMER_HEADS = 8

_C.PROTEIN.ESM_MAX_LENGTH = _C.PROTEIN.MAX_LENGTH
_C.PROTEIN.ESM_ADAPTER_LAYERS = _C.PROTEIN.ADAPTER_LAYERS
_C.PROTEIN.ESM_USE_TRANSFORMER = _C.PROTEIN.USE_TRANSFORMER
_C.PROTEIN.ESM_TRANSFORMER_LAYERS = _C.PROTEIN.TRANSFORMER_LAYERS
_C.PROTEIN.ESM_TRANSFORMER_HEADS = _C.PROTEIN.TRANSFORMER_HEADS

_C.CROSSINTENTION = CN()
_C.CROSSINTENTION.LAYER = 1
_C.CROSSINTENTION.NUM_HEAD = 8
_C.CROSSINTENTION.EMBEDDING_DIM = 128

_C.DECODER = CN()
_C.DECODER.NAME = "MLP"
_C.DECODER.IN_DIM = 256
_C.DECODER.HIDDEN_DIM = 512
_C.DECODER.OUT_DIM = 128
_C.DECODER.BINARY = 1

_C.SOLVER = CN()
_C.SOLVER.MAX_EPOCH = 15
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.NUM_WORKERS = 0
_C.SOLVER.LR = 1e-4
_C.SOLVER.USE_LD = True
_C.SOLVER.LR_DECAY = 0.5
_C.SOLVER.DECAY_INTERVAL = 5
_C.SOLVER.WEIGHT_DECAY = 1e-5
_C.SOLVER.SEED = 42

_C.RESULT = CN()
_C.RESULT.OUTPUT_DIR = r"../output/result/"
_C.RESULT.SAVE_MODEL = True

# Precomputed feature directories
#   FEATURE_DIR/unique_vit_features.pt            (from extract_unique_vit_features.py)
#   FEATURE_DIR/T5-XL/unique_protein_features.npy (from extract_unique_features.py)
_C.PRECOMPUTED = CN()
_C.PRECOMPUTED.USE_VIT_FEATURES = False
_C.PRECOMPUTED.FEATURE_DIR = r"../preprocessed_features"
_C.PRECOMPUTED.PLM_FEATURE_DIR = r"../preprocessed_features"
_C.PRECOMPUTED.ESM2_FEATURE_DIR = _C.PRECOMPUTED.PLM_FEATURE_DIR

def get_cfg_defaults():
    return _C.clone()
